# ===================
# Webserv config file
# ===================

server {
    listen 127.0.0.1:8080;
    server_name first.com;

	client_max_body_size 10;

	# location / {
	# 	methods GET;
	# 	root ./www/first;
	# 	index index.html;
	# 	autoindex on;
	# }

	location /upload {
		methods POST;
		root ./uploads;
		# upload_store ./uploads;
	}
}

# server {
#     listen 127.0.0.1:8080;
#     server_name second.com;

# 	location / {
# 		methods GET;
# 		root ./www/second;
# 		index index.html;
# 	}
# }

