# ===================
# Webserv config file
# ===================

server {
    listen 127.0.0.1:8080;
	server_name webserv.com;

	client_max_body_size 10M;

	error_page 403 /error_pages/403.html;
	error_page 404 /error_pages/404.html;
	error_page 500 /error_pages/500.html;

	# Static website
	# location / {
	# 	methods GET;
	# 	root ./www;
	# 	index index.html;
	# 	autoindex off;
	# }

	# # Upload endpoint
	# location /upload {
	# 	methods POST;
	# 	upload_store ./uploads;
	# }

	# # View and delete uploaded files
	# location /uploads {
	# 	methods GET DELETE;
	# 	root ./uploads;
	# 	autoindex on;
	# }

	# # CGI test
	# location /cgi-bin {
	# 	methods GET POST;
	# 	root /var/www/cgi-bin;
	# 	cgi .php /usr/bin/php-cgi;
	# }

	# location /cgi-bin {
	# 	methods GET POST;
	# 	root /home/tignatov/webserv_git/cgi-bin;
	# 	cgi .php /usr/bin/php-cgi;
	# }

	location /old {
		methods GET;
        return 301 "/new?from=old&x=1";
	}

	location /new {
    methods GET;
    root ./www;
    index index.html;
	}


	# location /uploads {
	# 	methods GET DELETE;
	# 	root ./uploads;
	# 	autoindex on;
	# }

	# location /upload {
	# 	methods POST;
	# 	root ./uploads;
	# 	upload_store ./uploads;
	# }

	# location / {
	# 	methods GET;
	# 	root /home/tignatov/webserv_git/www;
	# 	index index.html;
	# 	autoindex on;
	# }

	location / {
		methods GET;
		root /home/tignatov/webserv_git/www;
		index index.html;
		autoindex on;
	}

	location /public {
		methods GET;
		root /home/tignatov/webserv_git/www;
		autoindex on;
		index index.html;
	}

	location /upload {
		methods POST;
		root /home/tignatov/webserv_git/uploads;
		upload_store /home/tignatov/webserv_git/uploads;
	}

	location /cgi-bin {
		methods GET POST;
		root /home/tignatov/webserv_git/cgi-bin;
		cgi .php /usr/bin/php-cgi;
    	cgi .py  /usr/bin/python3;
	}


	location /uploads {
		methods GET;
		root /home/tignatov/webserv_git/uploads;
		autoindex on;
	}
}
