# ===================
# Webserv config file
# ===================

server {
	listen 127.0.0.1:8080;
	listen 0.0.0.0:8081;
	server_name webserv.com

	client_max_body_size 10M;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	location / {
		methods GET;
		root /var/www/site;
		index index.html;
		autoindex off;
	}

	location /public {
		methods GET;
		root /var/www/public;
		autoindex on;
		index index.html;
	}

	# Upload test
	location /upload {
		method POST;
		root /var/www/upload;
		upload_store /var/www/upload;
	}

	# CGI test
	location /cgi-bin {
		methods GET POST;
		root /var/www/cgi-bin;
		cgi .php /usr/bin/php-cgi;
	}

	location /old {
		methods GET;
		return 301 "/new?from=old&x=1"
	}

}